config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get '/driver', to: 'login#new'

  resources :sessions, :login, only: [:new, :create, :destroy]
  resources :order, :stock, :mobile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :current_driver
  before_action :user_signed_in?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_driver
    @current_driver ||= Driver.find_by(id: session[:driver_id])
  end

  #Check logged user
  protected

  def user_signed_in?
    return if current_user
    redirect_to new_session_path, notice: "Пожалуйста, пройдите авторизацию!" if current_driver.nil?
  end

  protected

  def driver_signed_in?
    return if current_driver
    redirect_to new_login_path, notice: "Пожалуйста, пройдите авторизацию!"
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    layout "sessions"
    skip_before_action :user_signed_in?, except: :destroy

    def new
    end

    def create
      driver = Driver.find_by(login: params[:login])
      if driver && driver.password == params[:password]
        session[:driver_id] = driver.id
        redirect_to mobile_index_path
      else
        redirect_to new_login_path, alert: "Неверный логин или пароль!"
      end
    end

    def destroy
      session[:driver_id] = nil
      redirect_to new_login_path, notice: "Сеанс работы завершен!"
    end


end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
  skip_before_action :user_signed_in?, except: :destroy
  before_action :driver_signed_in?

  def index
    @orders = Order.all.where(is_a_live: true, driver: current_driver)
  end

  protected

  def driver_signed_in?
    return if current_driver
    redirect_to new_login_path, notice: "Пожалуйста, пройдите авторизацию!"
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def index
    @orders = Order.all.where(is_a_live: true)
  end

  def new
    @order = Order.new
    @shops = Shop.all
    @drivers = Driver.all
  end

  def create
    shop = Shop.find(order_params[:shop])
    @order = Order.new(shop: shop.name, address: shop.address, pure_water: order_params[:pure_water], empty_bottle: 0, empty_bottle_back: 0,
                       dirty_bottle: order_params[:dirty_bottle], dirty_bottle_back: 0, date_of_completion: "не выполнена", driver: order_params[:driver])
    if @order.save
      redirect_to order_index_path, notice: 'Заявка добавлена в систему!'
    else
      render action: 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
    @shops = Shop.all
    @drivers = Driver.all

    @shop = Shop.find_by(name: @order.shop)
    @driver = Driver.find_by(name: @order.driver)
  end

  def update
    shop = Shop.find(order_params[:shop])
    @order = Order.find(params[:id])

    if @order.update(shop: shop.name, address: shop.address, pure_water: order_params[:pure_water], empty_bottle: 0, empty_bottle_back: 0,
                     dirty_bottle: order_params[:dirty_bottle], dirty_bottle_back: 0, date_of_completion: "не выполнена", driver: order_params[:driver])

      redirect_to order_index_path, notice: 'Заявка добавлена в систему!'
    else
      render action: 'new'
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def destroy
    order = Order.find(params[:id])
    order.update(is_a_live: false)
    redirect_to order_index_path, notice: 'Заявка удалена из системы!'
  end

  def order_params
    params.require(:order).permit(:shop, :pure_water, :dirty_bottle, :driver)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "sessions"
  skip_before_action :user_signed_in?, except: :destroy

  def new
  end

  def create
    user = User.find_by(login: params[:login])
    if user && user.password == params[:password]
      session[:user_id] = user.id
      redirect_to order_index_path
    else
      redirect_to new_session_path, alert: "Неверный логин или пароль!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, notice: "Сеанс работы завершен!"
  end
end

app/controllers/stock_controller.rb
class StockController < ApplicationController
  def index
    @stock = Stock.last
  end

  def new
    @stock_new = Stock.new
  end

  def create
    stock = Stock.last

    if stock_params[:pure_water].nil?
      new_pure_water = 0
    else
      stock_params[:pure_water].to_i > 0 ? new_pure_water = stock.pure_water + stock_params[:pure_water].to_i : new_pure_water = stock.pure_water + stock_params[:pure_water].to_i * -1
    end

    if stock_params[:empty_bottle].nil?
      new_empty_bottle = 0
    else
      stock_params[:empty_bottle].to_i > 0 ? new_empty_bottle = stock.empty_bottle + stock_params[:empty_bottle].to_i : new_empty_bottle = stock.empty_bottle + stock_params[:empty_bottle].to_i * -1

    end

    if stock_params[:empty_bottle].nil?
      new_dirty_bottle = 0
    else
      stock_params[:dirty_bottle].to_i > 0 ? new_dirty_bottle = stock.dirty_bottle + stock_params[:dirty_bottle].to_i : new_dirty_bottle = stock.dirty_bottle + stock_params[:dirty_bottle].to_i * -1

    end

    @stock = Stock.new(pure_water: new_pure_water, empty_bottle: new_empty_bottle, dirty_bottle: new_dirty_bottle, who_makes_changes: current_user.name)

    if @stock.save
      redirect_to stock_index_path, notice: 'Приход обнавлен!'
    else
      render action: 'new'
    end
  end

  def stock_params
    params.require(:stock).permit(:pure_water, :empty_bottle, :dirty_bottle)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Кофе Фреш</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Кофе Фреш</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

  <%= stylesheet_link_tag    'sessions', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/login/new.html.erb
<%= form_tag("/login", method: "post", class: 'form-signin') do %>
    <% if flash[:alert] %>
        <div class="alert alert-danger"> <%= flash[:alert] %> </div>
    <% end %>
    <% if notice %>
        <div class="alert alert-info"> <%= notice %> </div>
    <% end %>

    <%= text_field_tag :login, params[:login], class: 'form-control', placeholder: 'имя', type: 'login' %>
    <%= text_field_tag :password, params[:password], class: 'form-control', placeholder: 'пароль', type: 'password', id: 'inputPassword' %>

    <%= submit_tag 'Войти в систему', class: 'btn btn-lg btn-primary btn-block' %>
<% end %>

app/views/mobile/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <% if notice %>
          <br/>
          <div class="alert alert-info"> <%= notice %> </div>
      <% end %>
      <%= link_to "Выйти", login_url(current_driver), class: 'driver_btn_exit', :method => "delete" %>

      <br><br>

      <% if !@orders.blank? %>

          <% @orders.each do |order| %>
              <%= link_to order.shop, order, class: 'driver_btn', role: 'button' %>
              <%= order.address %>
              <h5>Вода: <%= order.pure_water %> | Отработка: <%= order.dirty_bottle %></h5>
              <hr>
          <% end %>
      <% else %>
          <div class="alert alert-info"> Нет заявок.</div>
      <% end %>

    </div>
  </div>
</div>

app/views/order/edit.html.erb
<%= render('patrial/navbar', menu: {active: "новая"}) %>

<div class="container">
  <div class="row">
    <div class="col-md-8">


      <% if @order.errors.any? %>
          <div id="error_explanation">

            <% @order.errors.full_messages.each do |msg| %>
                <div class="alert alert-warning" role="alert"><%= msg %></div>
            <% end %>
          </div>
      <% end %>

      <%= form_for @order, url: order_path do |form| %>
          <br/>
          <%= form.select(:shop, @shops.collect {|a| [a.name, a.id]}, {}, { class: 'form-control' }) -%>
          <br/>
          <%= form.text_field :pure_water, class: "form-control", placeholder: "Сколько бутылок с чистой водой", maxlength: 10 %>
          <br/>

          <%= form.text_field :dirty_bottle, class: "form-control", placeholder: "Сколько бутылок для отработки", maxlength: 10 %>
          <br/>
          <%= form.select(:driver, @drivers.collect {|a| [a.name, a.id]}, {}, { class: 'form-control' }) -%>
          <br/>
          <%= form.submit 'Добавить', class: "btn btn-primary" %> <%= link_to 'Отмена', order_index_path, class: 'btn btn-default btn', role: 'button' %>
      <% end %>
    </div>
  </div>
</div>

app/views/order/index.html.erb
<%= render('patrial/navbar', menu: {active: "заявки"}) %>

<div class="container">
  <div class="row">
    <div class="col-md-12">

      <% if notice %>
          <br />
          <div class="alert alert-info"> <%= notice %> </div>
      <% end %>


      <% if !@orders.blank? %>

          <table class="table table-hover">

            <thead>
            <tr>
              <th>Куда</th>
              <th>Адрес</th>
              <th>Вода (бутылки)</th>
              <th>Отработка (бутылки)</th>
              <th></th>
              <th></th>
            </tr>
            </thead>

            <tbody>
            <% @orders.each do |order| %>
                <tr>
                  <td><%= order.shop %></td>
                  <td><%= order.address %></td>
                  <td><%= order.pure_water %></td>
                  <td><%= order.dirty_bottle %></td>
                  <td><%= link_to 'Изменить', edit_order_path(order) %></td>
                  <td><%= button_to 'Удалить', order, class:'btn btn-danger', data: { confirm: 'Вы уверены?' }, method: :delete %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
      <% else %>
          <div class="alert alert-info"> Нет заявок.</div>
      <% end %>

      <br />
      <%= link_to 'Добавить заявку на поставку воды', new_order_path, class: 'btn btn-default btn', role: 'button' %>
    </div>
  </div>
</div>

app/views/order/new.html.erb
<%= render('patrial/navbar', menu: {active: "новая"}) %>

<div class="container">
  <div class="row">
    <div class="col-md-8">


      <% if @order.errors.any? %>
          <div id="error_explanation">

            <% @order.errors.full_messages.each do |msg| %>
                <div class="alert alert-warning" role="alert"><%= msg %></div>
            <% end %>
          </div>
      <% end %>

      <%= form_for @order, url: order_index_path do |form| %>
          <br/>
          <%= form.select(:shop, @shops.collect {|a| [a.name, a.id]}, {}, { class: 'form-control' }) -%>
          <br/>
          <%= form.text_field :pure_water, class: "form-control", placeholder: "Сколько бутылок с чистой водой", maxlength: 10 %>
          <br/>

          <%= form.text_field :dirty_bottle, class: "form-control", placeholder: "Сколько бутылок для отработки", maxlength: 10 %>
          <br/>
          <%= form.select(:driver, @drivers.collect {|a| [a.name, a.id]}, {}, { class: 'form-control' }) -%>
          <br/>
          <%= form.submit 'Добавить', class: "btn btn-primary" %> <%= link_to 'Отмена', order_index_path, class: 'btn btn-default btn', role: 'button' %>
      <% end %>
    </div>
  </div>
</div>

app/views/order/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <br>
      <%= link_to 'Назад', mobile_index_path, class: 'btn btn-default btn-lg', role: 'button' %>
      <br> <br>
      <div class="jumbotron">
        <h4><%= @order.shop %></h4>
        <h4><%= @order.address %></h4>
        <h4>Отдать чистой воды: <%= @order.pure_water %></h4>
        <h4>Отдать для отработки: <%= @order.dirty_bottle %></h4>
        <br>
        <%= form_for @order, url: order_index_path do |form| %>
            <%= form.text_field :empty_bottle_back, class: "form-control", placeholder: "Сколько забрал бутылок с чистой водой", maxlength: 10 %>
            <br>
            <%= form.text_field :dirty_bottle_back, class: "form-control", placeholder: "Сколько бутылок с чистой водой", maxlength: 10 %>
            <br>
            <%= submit_tag 'Отгрузил', class: 'btn btn-primary btn-lg' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/patrial/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Водный баланс</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li <% if menu[:active] == "склад" %> class="active"
            <% end %> ><a href="/stock">Склад</a></li>
        <li <% if menu[:active] == "заявки" %> class="active"
            <% end %> ><a href="/order">Заявки</a></li>
        <li<% if menu[:active] == "новая" %> class="active"
           <% end %> ><a href="/order/new">Новая заявка</a></li>
        <li <% if menu[:active] == "статистика" %> class="active"
            <% end %> ><a href="/product">Статистика</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to "Выйти", session_url(current_user), :method => "delete" %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/stock/index.html.erb
<%= render('patrial/navbar', menu: {active: "склад"}) %>

<div class="container">
  <div class="row">
    <div class="col-md-12">

      <% if notice %>
          <br />
          <div class="alert alert-info"> <%= notice %> </div>
      <% end %>

      <h4>Кол-во бутылок с водой: <%= @stock.pure_water %></h4>
      <h4>Кол-во пустых бутылок для воды: <%= @stock.empty_bottle %></h4>
      <h4>Кол-во бутылок для отработки: <%= @stock.dirty_bottle %></h4>
      <br>
      <%= link_to 'Поставить на приход', new_stock_path, class: 'btn btn-default btn', role: 'button' %>
    </div>
  </div>
</div>

app/views/stock/new.html.erb
<%= render('patrial/navbar', menu: {active: "склад"}) %>

<div class="container">
  <div class="row">
    <div class="col-md-8">


      <% if @stock_new.errors.any? %>
          <div id="error_explanation">

            <% @stock_new.errors.full_messages.each do |msg| %>
                <div class="alert alert-warning" role="alert"><%= msg %></div>
            <% end %>
          </div>
      <% end %>

      <%= form_for @stock_new, url: stock_index_path do |form| %>
          <%= form.text_field :pure_water, class: "form-control", placeholder: "Сколько бутылок с чистой водой", maxlength: 10 %>
          <br/>
          <%= form.text_field :empty_bottle, class: "form-control", placeholder: "Сколько пустых бутылок для чистой воды", maxlength: 10 %>
          <br/>
          <%= form.text_field :dirty_bottle, class: "form-control", placeholder: "Сколько бутылок для отработки", maxlength: 10 %>
          <br/>
          <%= form.submit 'Добавить', class: "btn btn-primary" %> <%= link_to 'Отмена', stock_index_path, class: 'btn btn-default btn', role: 'button' %>
      <% end %>
    </div>
  </div>
</div>